<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sasmodel" nsURI="http://www.example.org/sasmodel" nsPrefix="sasmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Subsystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="probe" upperBound="-1"
        eType="#//Probe" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measuredoutput" upperBound="-1"
        eType="#//MeasuredOutput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Managing" eSuperTypes="#//Subsystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlloopmanager" lowerBound="1"
        eType="#//ControlLoopManager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Managed" eSuperTypes="#//Subsystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlLoopManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlloop" lowerBound="1"
        upperBound="-1" eType="#//ControlLoop"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synchronized" eSuperTypes="#//ControlLoopManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinated" eSuperTypes="#//ControlLoopManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="Independent" eSuperTypes="#//ControlLoopManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitor" lowerBound="1"
        upperBound="-1" eType="#//Monitor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzer" lowerBound="1"
        upperBound="-1" eType="#//Analyzer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="planner" upperBound="-1"
        eType="#//Planner" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executor" lowerBound="1"
        upperBound="-1" eType="#//Executor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Monitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" lowerBound="1"
        upperBound="-1" eType="#//Sensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Analyzer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledge" lowerBound="1"
        eType="#//Knowledge"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Planner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledge" lowerBound="1"
        eType="#//Knowledge"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Executor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="effector" lowerBound="1"
        upperBound="-1" eType="#//Effector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Knowledge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceinput" lowerBound="1"
        upperBound="-1" eType="#//ReferenceInput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceInput">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="probe" eType="#//Probe"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsystem" eType="#//Subsystem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasuredOutput">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Probe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
  </eClassifiers>
</ecore:EPackage>
