/**
 * generated by Xtext 2.21.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DC Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getOnly <em>Only</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getT <em>T</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getCan <em>Can</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getElementType <em>Element Type</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getType <em>Type</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getCannot <em>Cannot</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getOnly2 <em>Only2</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getMust <em>Must</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getEntityType <em>Entity Type</em>}</li>
 * </ul>
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl()
 * @model
 * @generated
 */
public interface DCDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Only</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Only</em>' containment reference.
   * @see #setOnly(Only)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl_Only()
   * @model containment="true"
   * @generated
   */
  Only getOnly();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getOnly <em>Only</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Only</em>' containment reference.
   * @see #getOnly()
   * @generated
   */
  void setOnly(Only value);

  /**
   * Returns the value of the '<em><b>T</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' reference.
   * @see #setT(DCLStructureElement)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl_T()
   * @model
   * @generated
   */
  DCLStructureElement getT();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getT <em>T</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>T</em>' reference.
   * @see #getT()
   * @generated
   */
  void setT(DCLStructureElement value);

  /**
   * Returns the value of the '<em><b>Can</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Can</em>' containment reference.
   * @see #setCan(Can)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl_Can()
   * @model containment="true"
   * @generated
   */
  Can getCan();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getCan <em>Can</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Can</em>' containment reference.
   * @see #getCan()
   * @generated
   */
  void setCan(Can value);

  /**
   * Returns the value of the '<em><b>Element Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Type</em>' containment reference.
   * @see #setElementType(ElementType)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl_ElementType()
   * @model containment="true"
   * @generated
   */
  ElementType getElementType();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getElementType <em>Element Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element Type</em>' containment reference.
   * @see #getElementType()
   * @generated
   */
  void setElementType(ElementType value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(DCLStructureElement)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl_Type()
   * @model
   * @generated
   */
  DCLStructureElement getType();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(DCLStructureElement value);

  /**
   * Returns the value of the '<em><b>Cannot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cannot</em>' containment reference.
   * @see #setCannot(Cannot)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl_Cannot()
   * @model containment="true"
   * @generated
   */
  Cannot getCannot();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getCannot <em>Cannot</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cannot</em>' containment reference.
   * @see #getCannot()
   * @generated
   */
  void setCannot(Cannot value);

  /**
   * Returns the value of the '<em><b>Only2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Only2</em>' containment reference.
   * @see #setOnly2(Only2)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl_Only2()
   * @model containment="true"
   * @generated
   */
  Only2 getOnly2();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getOnly2 <em>Only2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Only2</em>' containment reference.
   * @see #getOnly2()
   * @generated
   */
  void setOnly2(Only2 value);

  /**
   * Returns the value of the '<em><b>Must</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Must</em>' containment reference.
   * @see #setMust(Must)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl_Must()
   * @model containment="true"
   * @generated
   */
  Must getMust();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getMust <em>Must</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Must</em>' containment reference.
   * @see #getMust()
   * @generated
   */
  void setMust(Must value);

  /**
   * Returns the value of the '<em><b>Entity Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Type</em>' containment reference.
   * @see #setEntityType(EntityType)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCDecl_EntityType()
   * @model containment="true"
   * @generated
   */
  EntityType getEntityType();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCDecl#getEntityType <em>Entity Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Type</em>' containment reference.
   * @see #getEntityType()
   * @generated
   */
  void setEntityType(EntityType value);

} // DCDecl
