/**
 * generated by Xtext 2.21.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DCL Component Interface</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCLComponentInterface#getComponent <em>Component</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCLComponentInterface#getInterfaceType <em>Interface Type</em>}</li>
 * </ul>
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCLComponentInterface()
 * @model
 * @generated
 */
public interface DCLComponentInterface extends DCLStructureElement
{
  /**
   * Returns the value of the '<em><b>Component</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' reference.
   * @see #setComponent(DCLStructureElement)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCLComponentInterface_Component()
   * @model
   * @generated
   */
  DCLStructureElement getComponent();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCLComponentInterface#getComponent <em>Component</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component</em>' reference.
   * @see #getComponent()
   * @generated
   */
  void setComponent(DCLStructureElement value);

  /**
   * Returns the value of the '<em><b>Interface Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface Type</em>' containment reference.
   * @see #setInterfaceType(InterfaceType)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCLComponentInterface_InterfaceType()
   * @model containment="true"
   * @generated
   */
  InterfaceType getInterfaceType();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DCLComponentInterface#getInterfaceType <em>Interface Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interface Type</em>' containment reference.
   * @see #getInterfaceType()
   * @generated
   */
  void setInterfaceType(InterfaceType value);

} // DCLComponentInterface
