/**
 * generated by Xtext 2.21.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DCL Module</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCLModule()
 * @model
 * @generated
 */
public interface DCLModule extends DCLStructureElement
{
} // DCLModule
