/**
 * generated by Xtext 2.21.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interface Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.InterfaceType#getInterfaceTypeName <em>Interface Type Name</em>}</li>
 * </ul>
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getInterfaceType()
 * @model
 * @generated
 */
public interface InterfaceType extends EObject
{
  /**
   * Returns the value of the '<em><b>Interface Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface Type Name</em>' attribute.
   * @see #setInterfaceTypeName(String)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getInterfaceType_InterfaceTypeName()
   * @model
   * @generated
   */
  String getInterfaceTypeName();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.InterfaceType#getInterfaceTypeName <em>Interface Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interface Type Name</em>' attribute.
   * @see #getInterfaceTypeName()
   * @generated
   */
  void setInterfaceTypeName(String value);

} // InterfaceType
