/**
 * generated by Xtext 2.21.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Only</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.Only#getOnly <em>Only</em>}</li>
 * </ul>
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getOnly()
 * @model
 * @generated
 */
public interface Only extends EObject
{
  /**
   * Returns the value of the '<em><b>Only</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Only</em>' attribute.
   * @see #setOnly(String)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getOnly_Only()
   * @model
   * @generated
   */
  String getOnly();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.Only#getOnly <em>Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Only</em>' attribute.
   * @see #getOnly()
   * @generated
   */
  void setOnly(String value);

} // Only
