/**
 * generated by Xtext 2.21.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Only2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.Only2#getOnly2 <em>Only2</em>}</li>
 * </ul>
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getOnly2()
 * @model
 * @generated
 */
public interface Only2 extends EObject
{
  /**
   * Returns the value of the '<em><b>Only2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Only2</em>' attribute.
   * @see #setOnly2(String)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getOnly2_Only2()
   * @model
   * @generated
   */
  String getOnly2();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.Only2#getOnly2 <em>Only2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Only2</em>' attribute.
   * @see #getOnly2()
   * @generated
   */
  void setOnly2(String value);

} // Only2
