/**
 * generated by Xtext 2.16.0
 */
package br.ufscar.sas.xtext.sasdsl.ui;

import br.ufscar.sas.xtext.sasdsl.ui.AbstractSasDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SasDslUiModule extends AbstractSasDslUiModule {
  public SasDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
