/**
 * generated by Xtext 2.16.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl.impl;

import br.ufscar.sas.xtext.sasdsl.sasDsl.ArchitectureDefinition;
import br.ufscar.sas.xtext.sasdsl.sasDsl.DSLManaged;
import br.ufscar.sas.xtext.sasdsl.sasDsl.DSLManaging;
import br.ufscar.sas.xtext.sasdsl.sasDsl.DSLRules;
import br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Architecture Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.impl.ArchitectureDefinitionImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.impl.ArchitectureDefinitionImpl#getManaging <em>Managing</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.impl.ArchitectureDefinitionImpl#getManaged <em>Managed</em>}</li>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.impl.ArchitectureDefinitionImpl#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ArchitectureDefinitionImpl extends MinimalEObjectImpl.Container implements ArchitectureDefinition
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getManaging() <em>Managing</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getManaging()
   * @generated
   * @ordered
   */
  protected EList<DSLManaging> managing;

  /**
   * The cached value of the '{@link #getManaged() <em>Managed</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getManaged()
   * @generated
   * @ordered
   */
  protected EList<DSLManaged> managed;

  /**
   * The cached value of the '{@link #getRules() <em>Rules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRules()
   * @generated
   * @ordered
   */
  protected EList<DSLRules> rules;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ArchitectureDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SasDslPackage.Literals.ARCHITECTURE_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SasDslPackage.ARCHITECTURE_DEFINITION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DSLManaging> getManaging()
  {
    if (managing == null)
    {
      managing = new EObjectContainmentEList<DSLManaging>(DSLManaging.class, this, SasDslPackage.ARCHITECTURE_DEFINITION__MANAGING);
    }
    return managing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DSLManaged> getManaged()
  {
    if (managed == null)
    {
      managed = new EObjectContainmentEList<DSLManaged>(DSLManaged.class, this, SasDslPackage.ARCHITECTURE_DEFINITION__MANAGED);
    }
    return managed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DSLRules> getRules()
  {
    if (rules == null)
    {
      rules = new EObjectContainmentEList<DSLRules>(DSLRules.class, this, SasDslPackage.ARCHITECTURE_DEFINITION__RULES);
    }
    return rules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGING:
        return ((InternalEList<?>)getManaging()).basicRemove(otherEnd, msgs);
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGED:
        return ((InternalEList<?>)getManaged()).basicRemove(otherEnd, msgs);
      case SasDslPackage.ARCHITECTURE_DEFINITION__RULES:
        return ((InternalEList<?>)getRules()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SasDslPackage.ARCHITECTURE_DEFINITION__NAME:
        return getName();
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGING:
        return getManaging();
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGED:
        return getManaged();
      case SasDslPackage.ARCHITECTURE_DEFINITION__RULES:
        return getRules();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SasDslPackage.ARCHITECTURE_DEFINITION__NAME:
        setName((String)newValue);
        return;
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGING:
        getManaging().clear();
        getManaging().addAll((Collection<? extends DSLManaging>)newValue);
        return;
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGED:
        getManaged().clear();
        getManaged().addAll((Collection<? extends DSLManaged>)newValue);
        return;
      case SasDslPackage.ARCHITECTURE_DEFINITION__RULES:
        getRules().clear();
        getRules().addAll((Collection<? extends DSLRules>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SasDslPackage.ARCHITECTURE_DEFINITION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGING:
        getManaging().clear();
        return;
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGED:
        getManaged().clear();
        return;
      case SasDslPackage.ARCHITECTURE_DEFINITION__RULES:
        getRules().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SasDslPackage.ARCHITECTURE_DEFINITION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGING:
        return managing != null && !managing.isEmpty();
      case SasDslPackage.ARCHITECTURE_DEFINITION__MANAGED:
        return managed != null && !managed.isEmpty();
      case SasDslPackage.ARCHITECTURE_DEFINITION__RULES:
        return rules != null && !rules.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ArchitectureDefinitionImpl
