/**
 * generated by Xtext 2.16.0
 */
package br.ufscar.sas.xtext.sasdsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SasDslIdeModule /* implements AbstractSasDslIdeModule  */{
}
