/*
 * generated by Xtext 2.20.0
 */
package br.ufscar.sas.xtext.sasdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSasDslScopeProvider extends DelegatingScopeProvider {
}
