/**
 * generated by Xtext 2.10.0
 */
package br.ufscar.sas.xtext.sasdsl.validation;

import br.ufscar.sas.xtext.sasdsl.validation.AbstractSasDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SasDslValidator extends AbstractSasDslValidator {
}
